"""FuzzForge modules SDK models.

This module provides backward-compatible exports for all model types.
For Core SDK compatibility, use imports from `fuzzforge_modules_sdk.api.models.mod`.
"""

from enum import StrEnum
from pathlib import Path  # noqa: TC003 (required by pydantic at runtime)

from pydantic import ConfigDict

# Re-export from mod.py for Core SDK compatibility
from fuzzforge_modules_sdk.api.models.mod import (
    Base,
    FuzzForgeModuleInputBase,
    FuzzForgeModuleResource,
    FuzzForgeModuleResources,
    FuzzForgeModulesSettingsBase,
    FuzzForgeModulesSettingsType,
)


class FuzzForgeModuleArtifacts(StrEnum):
    """Enumeration of artifact types."""

    #: The artifact is an asset.
    ASSET = "asset"


class FuzzForgeModuleArtifact(Base):
    """An artifact generated by the module during its run."""

    #: The description of the artifact.
    description: str
    #: The type of the artifact.
    kind: FuzzForgeModuleArtifacts
    #: The name of the artifact.
    name: str
    #: The path to the artifact on disk.
    path: Path


class FuzzForgeModuleResults(StrEnum):
    """Module execution result enumeration."""

    SUCCESS = "success"
    FAILURE = "failure"


class FuzzForgeModuleStatus(StrEnum):
    """Possible statuses emitted by a running module."""

    #: Module is setting up its environment.
    INITIALIZING = "initializing"
    #: Module is actively running.
    RUNNING = "running"
    #: Module finished successfully.
    COMPLETED = "completed"
    #: Module encountered an error.
    FAILED = "failed"
    #: Module was stopped by the orchestrator (SIGTERM).
    STOPPED = "stopped"


class FuzzForgeModuleOutputBase(Base):
    """The (standardized) output of a FuzzForge module."""

    #: The collection of artifacts generated by the module during its run.
    artifacts: list[FuzzForgeModuleArtifact]
    #: The path to the logs.
    logs: Path
    #: The result of the module's run.
    result: FuzzForgeModuleResults


__all__ = [
    # Core SDK compatible exports
    "Base",
    "FuzzForgeModuleInputBase",
    "FuzzForgeModuleResource",
    "FuzzForgeModuleResources",
    "FuzzForgeModulesSettingsBase",
    "FuzzForgeModulesSettingsType",
    # OSS-specific exports (also used in OSS modules)
    "FuzzForgeModuleArtifact",
    "FuzzForgeModuleArtifacts",
    "FuzzForgeModuleOutputBase",
    "FuzzForgeModuleResults",
    "FuzzForgeModuleStatus",
]
