line-length = 120

[lint]
select = [ "ALL" ]
ignore = [
    "COM812",   # conflicts with the formatter
    "D203",     # conflicts with 'D211'
    "D213",     # conflicts with 'D212'
]

[lint.per-file-ignores]
"tests/*" = [
    "PLR2004",  # allowing comparisons using unamed numerical constants in tests
    "S101",     # allowing 'assert' statements in tests
]
