[mypy]
plugins = pydantic.mypy
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-testcontainers.*]
ignore_missing_imports = True
